# Generated by Django 5.2.13 on 2026-05-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_author_alter_article_publisher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_approve_article', 'Can approve article')]},
        ),
    ]
